name: Villages
main: com.stefthedev.villages.Villages
version: BETA-3.0
author: StefTheDev

softdepend: [PlaceholderAPI, WorldGuard]

commands:
  village:
    description: The village command.
    aliases:
      - villages
      - v