name: Villages
main: com.stefthedev.villages.Villages
version: BETA-5.3
author: StefTheDev
api-version: 1.13

softdepend: [PlaceholderAPI, WorldGuard]

commands:
  village:
    description: The village command.
    aliases:
      - villages
      - v